### PR TITLE
simpleJWT as a submodule

### PR DESCRIPTION
**Pull request by AliAbdollahiii**
Simple traceable JWT authentication example.

### CODE REVIEW

**Comment by thc202** [comment]
IMHO all the code should reside in this repo.

**Comment by AliAbdollahiii** [comment]
> IMHO all the code should reside in this repo.

Should I wait for the approval to update the submodule in the main repository?

**Comment by kingthorin** [comment]
@AliAbdollahiii any specific reason you want to submodule these? We intended this to the the authoritative repo for such examples, it seems like you just created those repos so there's no reason that content can't just be added here directly.

**Comment by AliAbdollahiii** [comment]
> @AliAbdollahiii any specific reason you want to submodule these? We intended this to the the authoritative repo for such examples, it seems like you just created those repos so there's no reason that content can't just be added here directly.

Hey @kingthorin 
I was actually confused and there was no specific reason. I'm going to close this and add the auth example codes directly into the repo if I'm not mistaken!?

**Comment by kingthorin** [comment]
It’ll still need to be a PR, but yes we would rather the code and components actually live in this repo.

**Comment by AliAbdollahiii** [comment]
https://github.com/zaproxy/auth-examples/pull/2#issuecomment-1480145795

**Pull request closed without merging**
